// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.7.0 (commit 02c67d121b0d08478eaf3512f479e7a326d39940).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { CompleteTask } from "./complete_task_reducer.ts";
export { CompleteTask };
import { CreateTask } from "./create_task_reducer.ts";
export { CreateTask };
import { DeleteTask } from "./delete_task_reducer.ts";
export { DeleteTask };
import { GetPendingReminders } from "./get_pending_reminders_reducer.ts";
export { GetPendingReminders };
import { MarkReminderSent } from "./mark_reminder_sent_reducer.ts";
export { MarkReminderSent };

// Import and reexport all table handle types
import { PendingReminderTableHandle } from "./pending_reminder_table.ts";
export { PendingReminderTableHandle };
import { ReminderTableHandle } from "./reminder_table.ts";
export { ReminderTableHandle };
import { TaskTableHandle } from "./task_table.ts";
export { TaskTableHandle };

// Import and reexport all types
import { PendingReminder } from "./pending_reminder_type.ts";
export { PendingReminder };
import { Reminder } from "./reminder_type.ts";
export { Reminder };
import { Task } from "./task_type.ts";
export { Task };
import { TaskStatus } from "./task_status_type.ts";
export { TaskStatus };

const REMOTE_MODULE = {
  tables: {
    pending_reminder: {
      tableName: "pending_reminder" as const,
      rowType: PendingReminder.getTypeScriptAlgebraicType(),
      primaryKey: "reminderId",
      primaryKeyInfo: {
        colName: "reminderId",
        colType: (PendingReminder.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    reminder: {
      tableName: "reminder" as const,
      rowType: Reminder.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Reminder.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    task: {
      tableName: "task" as const,
      rowType: Task.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Task.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    complete_task: {
      reducerName: "complete_task",
      argsType: CompleteTask.getTypeScriptAlgebraicType(),
    },
    create_task: {
      reducerName: "create_task",
      argsType: CreateTask.getTypeScriptAlgebraicType(),
    },
    delete_task: {
      reducerName: "delete_task",
      argsType: DeleteTask.getTypeScriptAlgebraicType(),
    },
    get_pending_reminders: {
      reducerName: "get_pending_reminders",
      argsType: GetPendingReminders.getTypeScriptAlgebraicType(),
    },
    mark_reminder_sent: {
      reducerName: "mark_reminder_sent",
      argsType: MarkReminderSent.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.7.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "CompleteTask", args: CompleteTask }
| { name: "CreateTask", args: CreateTask }
| { name: "DeleteTask", args: DeleteTask }
| { name: "GetPendingReminders", args: GetPendingReminders }
| { name: "MarkReminderSent", args: MarkReminderSent }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  completeTask(taskId: bigint) {
    const __args = { taskId };
    let __writer = new __BinaryWriter(1024);
    CompleteTask.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("complete_task", __argsBuffer, this.setCallReducerFlags.completeTaskFlags);
  }

  onCompleteTask(callback: (ctx: ReducerEventContext, taskId: bigint) => void) {
    this.connection.onReducer("complete_task", callback);
  }

  removeOnCompleteTask(callback: (ctx: ReducerEventContext, taskId: bigint) => void) {
    this.connection.offReducer("complete_task", callback);
  }

  createTask(title: string, description: string, deadlineMs: bigint, reminderCount: number) {
    const __args = { title, description, deadlineMs, reminderCount };
    let __writer = new __BinaryWriter(1024);
    CreateTask.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_task", __argsBuffer, this.setCallReducerFlags.createTaskFlags);
  }

  onCreateTask(callback: (ctx: ReducerEventContext, title: string, description: string, deadlineMs: bigint, reminderCount: number) => void) {
    this.connection.onReducer("create_task", callback);
  }

  removeOnCreateTask(callback: (ctx: ReducerEventContext, title: string, description: string, deadlineMs: bigint, reminderCount: number) => void) {
    this.connection.offReducer("create_task", callback);
  }

  deleteTask(taskId: bigint) {
    const __args = { taskId };
    let __writer = new __BinaryWriter(1024);
    DeleteTask.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("delete_task", __argsBuffer, this.setCallReducerFlags.deleteTaskFlags);
  }

  onDeleteTask(callback: (ctx: ReducerEventContext, taskId: bigint) => void) {
    this.connection.onReducer("delete_task", callback);
  }

  removeOnDeleteTask(callback: (ctx: ReducerEventContext, taskId: bigint) => void) {
    this.connection.offReducer("delete_task", callback);
  }

  getPendingReminders() {
    this.connection.callReducer("get_pending_reminders", new Uint8Array(0), this.setCallReducerFlags.getPendingRemindersFlags);
  }

  onGetPendingReminders(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_pending_reminders", callback);
  }

  removeOnGetPendingReminders(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_pending_reminders", callback);
  }

  markReminderSent(reminderId: bigint) {
    const __args = { reminderId };
    let __writer = new __BinaryWriter(1024);
    MarkReminderSent.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("mark_reminder_sent", __argsBuffer, this.setCallReducerFlags.markReminderSentFlags);
  }

  onMarkReminderSent(callback: (ctx: ReducerEventContext, reminderId: bigint) => void) {
    this.connection.onReducer("mark_reminder_sent", callback);
  }

  removeOnMarkReminderSent(callback: (ctx: ReducerEventContext, reminderId: bigint) => void) {
    this.connection.offReducer("mark_reminder_sent", callback);
  }

}

export class SetReducerFlags {
  completeTaskFlags: __CallReducerFlags = 'FullUpdate';
  completeTask(flags: __CallReducerFlags) {
    this.completeTaskFlags = flags;
  }

  createTaskFlags: __CallReducerFlags = 'FullUpdate';
  createTask(flags: __CallReducerFlags) {
    this.createTaskFlags = flags;
  }

  deleteTaskFlags: __CallReducerFlags = 'FullUpdate';
  deleteTask(flags: __CallReducerFlags) {
    this.deleteTaskFlags = flags;
  }

  getPendingRemindersFlags: __CallReducerFlags = 'FullUpdate';
  getPendingReminders(flags: __CallReducerFlags) {
    this.getPendingRemindersFlags = flags;
  }

  markReminderSentFlags: __CallReducerFlags = 'FullUpdate';
  markReminderSent(flags: __CallReducerFlags) {
    this.markReminderSentFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get pendingReminder(): PendingReminderTableHandle<'pending_reminder'> {
    // clientCache is a private property
    return new PendingReminderTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PendingReminder>(REMOTE_MODULE.tables.pending_reminder));
  }

  get reminder(): ReminderTableHandle<'reminder'> {
    // clientCache is a private property
    return new ReminderTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Reminder>(REMOTE_MODULE.tables.reminder));
  }

  get task(): TaskTableHandle<'task'> {
    // clientCache is a private property
    return new TaskTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Task>(REMOTE_MODULE.tables.task));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
